package fr.baretto.ollamassist.agent.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A single step in an execution plan.
 * Generated by the orchestrator via structured output.
 */
public record PlanStep(
    @JsonProperty(required = true)
    int stepNumber,

    @JsonProperty(required = true)
    AgentType agentType,

    @JsonProperty(required = true)
    String action,

    @JsonProperty(required = true)
    String justification,

    String expectedOutput,

    List<Integer> dependencies
) {}
