package fr.baretto.ollamassist.agent.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Execution plan generated by the orchestrator.
 * Displayed to user before execution for approval.
 */
public record Plan(
    @JsonProperty(required = true)
    String goal,

    @JsonProperty(required = true)
    List<PlanStep> steps,

    Integer estimatedDuration
) {
    public Plan {
        if (goal == null || goal.isBlank()) {
            throw new IllegalArgumentException("Goal cannot be null or empty");
        }
        if (steps == null || steps.isEmpty()) {
            throw new IllegalArgumentException("Plan must have at least one step");
        }
    }
}
